/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.lesports.qmt.tlive.api.common;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TextLiveMessageType implements org.apache.thrift.TEnum {
  TEXT(1),
  IMAGE(2),
  VOTE(3),
  VIDEO(4),
  MATCH_DATA(5),
  LINK(6),
  WEIBO(7);

  private final int value;

  private TextLiveMessageType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TextLiveMessageType findByValue(int value) { 
    switch (value) {
      case 1:
        return TEXT;
      case 2:
        return IMAGE;
      case 3:
        return VOTE;
      case 4:
        return VIDEO;
      case 5:
        return MATCH_DATA;
      case 6:
        return LINK;
      case 7:
        return WEIBO;
      default:
        return null;
    }
  }
}
