/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.lesports.qmt.transcode.model;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * http://wiki.letv.cn/pages/viewpage.action?pageId=60097273
 * 
 */
public enum LiveToVideoTaskStatus implements org.apache.thrift.TEnum {
  RECORDING(20),
  RECORD_SUCCESS(21),
  RECORD_FAIL(29),
  TRANSCODING(38),
  TRANSCODING_FAIL(39),
  TASK_FINISH(40);

  private final int value;

  private LiveToVideoTaskStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static LiveToVideoTaskStatus findByValue(int value) { 
    switch (value) {
      case 20:
        return RECORDING;
      case 21:
        return RECORD_SUCCESS;
      case 29:
        return RECORD_FAIL;
      case 38:
        return TRANSCODING;
      case 39:
        return TRANSCODING_FAIL;
      case 40:
        return TASK_FINISH;
      default:
        return null;
    }
  }
}
