/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.lesports.qmt.sbc.api.dto;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum LiveStatus implements org.apache.thrift.TEnum {
  LIVE_NOT_START(0),
  LIVING(1),
  LIVE_END(2);

  private final int value;

  private LiveStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static LiveStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return LIVE_NOT_START;
      case 1:
        return LIVING;
      case 2:
        return LIVE_END;
      default:
        return null;
    }
  }
}
